---
title: "plotting DTU"
output:
  html_document:
    df_print: paged
---

We will plot fraction expresssion in each condition on each axis, therefore divergence from x=y represents DTU between conditions 

```{r}
library(data.table)
library(ggplot2)
library(tidyr)
library(dplyr)
library(ggrepel)
```

Get expression data

```{r}
utrons_expression <- fread("../../../../../HCT-NMD_KD/JR_DTU/expression.dir/utrons_expression.txt")
tidy_expressions <- utrons_expression %>%
  separate(Sample, into=c("Cellline", "Condition", "Rep")) %>%
  extract(Condition, into =c("siRNA", "Inh"), regex="(.)(.+)")


med_frac <- tidy_expressions %>%
  group_by(transcript_id, gene_id, siRNA) %>%
  summarise(tr.expr=median(tr.expr),
            fract.expr=median(fract.expr))  %>%
  group_by(gene_id, siRNA) %>%
  mutate(gene.expr = sum(tr.expr))
```


```{r, fig.height=2, fig.width=3}
utrons <- read.delim("../../../../../HCT-NMD_KD/JR_DTU/expression.dir/csvdb_files/all_utrons_ids.txt")
utrons_med_frac <- filter(med_frac, transcript_id %in% utrons$transcript_id)
sig_dtu <- read.csv("../../../../../HCT-NMD_KD/JR_DTU/DTU.dir/siDSRed_vs_siUPF1/drim_dtu_stageR-screened.csv")

sig_dtu <- mutate(sig_dtu, sigDTU = transcript < 0.05)
utrons_med_frac %>%
  left_join(dplyr::select(sig_dtu, transcript_id=txID, sigDTU)) %>%
  replace_na(list(sigDTU=FALSE)) %>%
  mutate(fract.expr = (tr.expr+0.1)/(gene.expr+0.1)) %>%
  group_by(transcript_id) %>%
  filter(max(tr.expr)>2.5) %>% 
  pivot_wider(id_cols=c(gene_id, transcript_id, sigDTU), 
              names_from=siRNA,
              values_from=fract.expr)  %>% 
  ggplot() + aes(x=R, y=U, color=sigDTU, alpha=sigDTU) +
  geom_point(size=0.5) +
  theme_bw(base_size=8) +
  xlab("Tx/Gene in Control") +
  ylab("Tx/Gene in siUPF1") +
  coord_fixed() +
  theme(axis.text = element_text(size=8),
        aspect.ratio=0.75,
        legend.position = "none") + 
  scale_color_manual(values=c("black", "red")) + 
  scale_alpha_manual(values=c(0.5,1)) -> saveme
png("siUPF1_DTUtrons.png", height=2, width=3, units="in", res=1200)
saveme
dev.off()
```


```{r}

```